exclude_patterns:
  - "config/"
  - "examples/"
  - "db/"
  - "dist/*"
  - "lib/*"
  - "**/lib/**"
  - "**/routes/**"
  - "e2e/*"
  - "api/*"
  - "routes/*"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
